name: ComplianceGetReports
author: PrestaShopCorp
description: Get reports of a scan launch into API Compliance, launched after @prestashopcorp/github-action-compliance-send.
inputs:
  service:
    description: 'Compliance service'
    required: true
  version:
    description: 'Module version'
    required: true
  technical_name:
    description: 'Module technicalName'
    required: true
  token_uri:
    description: ''
    required: true
  cookie: 
    description: ''
    required: true
  client_id: 
    description: ''
    required: true
  client_secret:
    description: ''
    required: true
  grant_type: 
    description: ''
    required: true
  audience: 
    description: ''
    required: true
  scope: 
    description: ''
    required: true
  compliance_base_uri:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Get OAUTH token from oauth.prestashop.com
      uses: ./../../actions/auth-compliance
      id: get_oauth_token
      with:
        token_uri: ${{ inputs.token_uri }}
        cookie: ${{ inputs.cookie }}
        client_id: ${{ inputs.client_ids }}
        client_secret: ${{ inputs.client_secret }}
        grant_type: ${{ inputs.grant_type }}
        audience: ${{ inputs.audience }}
        scope: ${{ inputs.scope }}
    - name: init service name
      id: init_service_name
      shell: bash
      run: |
        echo SERVICE_NAME=$(echo ${{ inputs.service }} | sed -e "s/-api$//") >> $GITHUB_OUTPUT && exit 0
    - name: get-report for ${{ inputs.service }}
      shell: bash
      run: |
        curl --location --request GET "${{ inputs.compliance_base_uri }}/${{ steps.init_service_name.outputs.SERVICE_NAME }}/v1/report?technicalName=${{ inputs.technical_name }}&version=${{ inputs.version }}" \
          --header 'Accept: application/json' \
          --oauth2-bearer ${{ steps.get_oauth_token.outputs.TOKEN }} \
          --output report.json && exit 0
        jq --color-output . report.json | less -R && exit 0